chat_application/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [   
    path('', include('accounts.urls' , namespace= 'accounts')),
    path('', include('chats.urls' , namespace= 'chats')),
    path('', include('friends.urls' , namespace= 'friends')),
    path('admin/', admin.site.urls),   
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chats/urls.py
from django.urls import path
from . import views

app_name = "chats"

urlpatterns = [
    
    path('', views.chat, name = "chat"),
    path('chat/<str:username>/', views.chat_detail, name = "chat_detail"),
   
]

friends/urls.py
from django.urls import path
from . import views

app_name = "friends"

urlpatterns = [
    
    path('search/', views.search_friend, name = "search"),
    path('notification/', views.notification, name = "notification"),

    path('follow/<str:username>/', views.follow, name = "follow"),
    path('unfollow/<str:username>/', views.unfollow, name = "unfollow"),
    
    path('accept_follower/<str:username>/', views.accept_follower, name = "accept_follower"),
    path('remove_follower/<str:username>/', views.remove_follower, name = "remove_follower"),
]

friends/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Friend(models.Model):
    follower = models.ForeignKey(User,related_name= "follower", on_delete = models.CASCADE)
    following = models.ForeignKey(User,related_name= "following" ,on_delete = models.CASCADE)
    is_accepted =  models.BooleanField(default = False)
    created_at = models.DateTimeField(auto_now_add = True)
    

    def __str__(self):
        return f"{self.follower} following {self.following}"

friends/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import Friend 
from chats.models import ChatRoom

from accounts.models import Profile
from django.db.models import Q

@login_required
def notification(request):
    user = request.user
    followers = Friend.objects.filter(following=user, is_accepted=False).order_by('-created_at')
    
    return render(request, "friends/notification.html", {'followers': followers})
    
    
@login_required    
def search_friend(request):
    friends = Profile.objects.all().exclude(user = request.user)
    accepted_friends = Friend.objects.all()
    accepted_friend_ids = set()
    
    for relationship in accepted_friends:
        if relationship.follower == request.user and not relationship.is_accepted:
            accepted_friend_ids.add(relationship.following.id)
            
        if relationship.is_accepted and (relationship.follower == request.user or relationship.following == request.user ):
            accepted_friend_ids.add(relationship.follower.id)
            accepted_friend_ids.add(relationship.following.id)
    
    if request.method == "GET":
        search = request.GET.get("q")
        
        if search :
            if Profile.objects.filter(user__username__icontains = search).exists() :
                friends = Profile.objects.filter(user__username__icontains = search).exclude(user = request.user)
   
    return render(request, "friends/search.html", {'friends':friends, 'accepted_friends':accepted_friend_ids})


def follow(request,username):
    follower = request.user
    following = User.objects.get(username=username)
    friend,created = Friend.objects.get_or_create(follower=follower, following=following)
    friend.save()
    
    return redirect("friends:search")

    
def unfollow(request,username):
    user = request.user
    friend = User.objects.get(username = username)
    unfollow_friend = Friend.objects.filter(Q(follower=friend,following=user )|Q(follower=user,following=friend ))
    unfollow_friend.delete()
    messages = ChatRoom.objects.filter(Q(sender=friend, receiver=user)|Q(sender=user, receiver=friend))
    messages.delete()
    
    return redirect("friends:search")

def accept_follower(request,username):
    user = request.user
    accepted_follower = Friend.objects.filter(follower__username=username, following=user).update(is_accepted=True)
    
    return redirect("friends:notification")
    
def remove_follower(request, username):
    user = request.user
    removed_follower = Friend.objects.filter(follower__username=username, following=user)
    removed_follower.delete()
    
    return redirect("friends:notification")
    

templates/friends/notification.html
{% extends 'base.html' %}

{% block title %}
	<title>Notification</title>
{% endblock %}
	
{% block content %} 
<div class="contacts">
    <ul>
	{% if followers %}
		{% for follower in followers %}
        <li class="notification-contact">
            <div class="wrap">
                <img src="{{follower.follower.profile.thumbnail.url}}" alt="Friend 1">
                <div class="meta">
                    <p class="name">{{follower.follower.username}}</p>
                    
                </div>
              
                <a href="{% url 'friends:accept_follower' follower.follower.username %}"><button class="accept-button" >accept</button></a>
              <a href="{% url 'friends:remove_follower' follower.follower.username %}"><button class="remove-button" >remove</button></a>
            </div>
        </li>
		{% endfor %}
	{% else %}
		<h6>no notifications yet </h6> 
		
	{% endif %}
        
    </ul>
</div>
{% endblock %}
{% block script %}

<script>
let acceptButtons = document.querySelectorAll('.accept-button');
let removeButtons = document.querySelectorAll('.remove-button');

acceptButtons.forEach(function(acceptBtn, index) {
    let removeBtn = removeButtons[index];  

    acceptBtn.addEventListener('click', function() {                                  
        acceptBtn.textContent = 'accepted';
        acceptBtn.className = 'accepted-button';
        removeBtn.remove(); 
    });
});
</script>	
{% endblock %}   

templates/friends/search.html
{% extends 'base.html' %}

{% block title %}
    <title>Search</title>
{% endblock %}

{% block content %}
<form method="GET">
    <div class="search">
        <input type="text" name="q" placeholder="Search contacts...">
    </div>
</form>
<div class="contacts">
    <ul>
		{% if friends %}
        {% for friend in friends %}
        <li class="search-contact">
            <div class="wrap">
                <img src="{{ friend.thumbnail.url}}" alt="Friend 1">
                <div class="meta">
                    <p class="name">{{ friend.user.username }}</p>
                </div>
                {% if friend.user.id in accepted_friends %}
                    <a href="{% url 'friends:unfollow' friend.user.username %}"><button class="unfollow-button">following</button></a>
                {% else %}
				
                    <a href="{% url 'friends:follow' friend.user.username %}"><button class="follow-button">follow</button></a>
			
                {% endif %}
            </div>
        </li>
        {% endfor %}
	{% else %}
		<h6> not found ! </h6> 
		
	{% endif %}
        
    </ul>
</div>
{% endblock %}

{% block script %}
<script>

let buttons = document.querySelectorAll('.follow-button, .unfollow-button');

buttons.forEach(function(btn) {
    btn.addEventListener('click', function() {
        if (btn.textContent === 'follow') {
            btn.textContent = 'following';
            btn.classList.replace('follow-button', 'unfollow-button');
        } 
		else {
            btn.textContent = 'follow';
            btn.classList.replace('unfollow-button', 'follow-button');
        }
    });
});
</script>
{% endblock %}