chat_application/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [   
    path('', include('accounts.urls' , namespace= 'accounts')),
    path('', include('chats.urls' , namespace= 'chats')),
    path('', include('friends.urls' , namespace= 'friends')),
    path('admin/', admin.site.urls),   
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chats/urls.py
from django.urls import path
from . import views

app_name = "chats"

urlpatterns = [
    
    path('', views.chat, name = "chat"),
    path('chat/<str:username>/', views.chat_detail, name = "chat_detail"),
   
]

chats/models.py
from django.db import models
from friends.models import Friend
from django.contrib.auth.models import User
# Create your models here.


class ChatRoom(models.Model):
    sender = models.ForeignKey(User,related_name= "sender", on_delete = models.CASCADE)
    receiver = models.ForeignKey(User,related_name= "receiver", on_delete = models.CASCADE)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add = True)
    unread_messages = models.BooleanField(default = False)
    
    def __str__(self):
        return f"{self.sender.username} send to {self.receiver.username}"
        
    
    
    
    

chats/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from friends.models import Friend
from chats.models import ChatRoom
from django.db.models import Q

@login_required
def chat(request):
    user = request.user
    friends = Friend.objects.filter(Q(following=user)|Q(follower=user), is_accepted=True)
    
    for friend in friends :
        if friend.following == user:
            friend.unread_msg = ChatRoom.objects.filter(receiver = user, sender=friend.follower, unread_messages=False).count()
            try :
            
                friend.last_message_added =  ChatRoom.objects.filter(Q(sender=friend.follower, receiver=user)|Q(sender=user, receiver=friend.follower)).latest('timestamp') 
                
                
            except ChatRoom.DoesNotExist :
                friend.last_message_added = None
            
        else :
            friend.unread_msg = ChatRoom.objects.filter(receiver = user,sender=friend.following, unread_messages=False).count()
            
            try :
                friend.last_message_added =  ChatRoom.objects.filter(Q(sender=friend.following, receiver=user)|Q(sender=user, receiver=friend.following)).latest('timestamp')
                
            except ChatRoom.DoesNotExist :
                friend.last_message_added = None       
       
    return render(request,"chats/chat.html",{'friends':friends})
    
    
def chat_detail(request, username ):
    user = request.user
    friend = User.objects.get(username = username)
    
    messages = ChatRoom.objects.filter(Q(sender=friend, receiver=user)|Q(sender=user, receiver=friend)).order_by("timestamp")
    message_readed = ChatRoom.objects.filter(receiver = user,sender=friend, unread_messages=False).update(unread_messages=True)
    
   
    return render(request,"chats/chat_detail.html", {'friend':friend, 'messages':messages})

templates/chats/chat.html
{% extends 'base.html' %}

{% block title %}
	<title>Home</title>
{% endblock %}
	
{% block content %}

<div class="contacts">
    <ul>
	{% if friends %}
		{% for friend in friends %}
		{% if friend.follower == request.user %}
        <li class="contact">
		
			<a href="{% url 'chats:chat_detail' friend.following.username %}" style="text-decoration: none;">
				<div class="wrap">
				<div class="contact-info">
					<img src="{{friend.following.profile.thumbnail.url}}" alt="Friend 1">
					{% if friend.following.profile.get_online_status %}
					<span class="online-status"></span>
					{% endif %}
					</div>
					<div class="meta">
						<p class="name">{{friend.following.username}}</p>
						<p class="preview">{{friend.last_message_added.message|slice:'0:25'}}</p>
					</div>
					{% if not friend.unread_msg == 0  %}
					<span class="friend-badge">{{friend.unread_msg}}</span>
					{% endif %}
				</div>
			</a>
		
		</li>
		{% else %}
		<li class="contact">
		
			<a href="{% url 'chats:chat_detail' friend.follower.username %}" style="text-decoration: none;">
				<div class="wrap">
				<div class="contact-info">
					<img src="{{friend.follower.profile.thumbnail.url}}" alt="Friend 1">
					{% if friend.follower.profile.get_online_status %}
					<span class="online-status"></span>
					{% endif %}
					</div>
					<div class="meta">
						<p class="name">{{friend.follower.username}}</p>
						<p class="preview">{{friend.last_message_added.message|slice:'0:25'}}</p>
					</div>
					{% if not friend.unread_msg == 0  %}
					<span class="friend-badge">{{friend.unread_msg}}</span>
					{% endif %}
				</div>
			</a>
		
		</li>
		{% endif %}
		{% endfor %}
	{% else %}
		<h6>no friends yet </h6> 
		
	{% endif %}
		
        
    </ul>
</div>

{% endblock %}

templates/chats/chat_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chat</title>
    <link rel="stylesheet" href="{% static 'css/chat.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
    <div id="frame">
        <div id="chat-area" class="content hidden">
            <div class="chat-header">
                <a href="{% url 'chats:chat' %}">
                    <button id="back-button"><i class="fa fa-arrow-left"></i></button>
                </a>
                <div class="friend-info">
                    <img id="chat-img" src="{{ friend.profile.thumbnail.url }}" alt="Friend's Image" class="friend-img">
                    {% if friend.profile.get_online_status %}
                        <span class="online-status"></span>
                    {% endif %}
                </div>
                <p id="chat-name">{{ friend }}</p>
            </div>
            <div class="messages">
			{% for message in messages %}
			
				<ul>
					<li class="
							{% if message.sender == request.user %}
							sent
							{% else %}
							replies
							{% endif %}

					"> 
						<p>  {{message.message}}  </p> 
						<span class="chat-time right">  {{message.timestamp|date:'h:i A'}}  </span> 
					</li>
        
				</ul>
			{% endfor %}
                <ul id="id_content">
				</ul>
            </div>
            <div class="message-input">
                <input type="text" id="id_message_send_input" placeholder="Write a message...">
                <button type="submit" id="id_message_send_button"><i class="fa fa-paper-plane"></i></button>
            </div>
        </div>
    </div>

    <script>
    const chatSocket = new WebSocket("ws://" + window.location.host + "/ws/chat/" + "{{ friend }}/");

    chatSocket.onopen = function(e) {
        console.log("The connection was set up successfully!");
    };

    chatSocket.onclose = function(e) {
        console.log("Something unexpected happened!");
    };

    document.getElementById('id_message_send_input').focus();
    document.getElementById('id_message_send_input').onkeyup = function(e) {
        if (e.keyCode === 13) {
            document.getElementById('id_message_send_button').click();
        }
    };

    const sendButton = document.getElementById('id_message_send_button');
    sendButton.addEventListener('click', function(e) {
        const message = document.getElementById('id_message_send_input').value;
        if (message) {
			const time = new Date().toLocaleTimeString("en-US", {
				hour: '2-digit',
				minute: '2-digit',
				hour12: true,
				timeZone: 'GMT',
			});

            chatSocket.send(JSON.stringify({
                'sender': "{{ request.user.username }}",  
				'receiver': "{{ friend }}",
                'message': message,
                'time': time,
            }));
            document.getElementById('id_message_send_input').value = "";  
        }
    });

    chatSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);
        var isUser = (data.sender === "{{ request.user.username }}");  
        var chat = document.getElementById('id_content');
        const source = isUser ? 'sent' : 'replies';
        
        chat.innerHTML += 
            '<li class="' + source + '">' +
            '<p>' + data.message + '</p>' +
            '<span class="chat-time right">' + data.time + '</span>' +
            '</li>';
        
        chat.scrollTop = chat.scrollHeight ;
    };
    </script>
</body>
</html>