accounts/urls.py
from django.urls import path
from . import views
from django.urls import reverse_lazy
from django.contrib.auth import views as auth
app_name = "accounts"

urlpatterns = [

    path('settings/', views.settings, name = "settings"),
    path('edit-profile/',views.EditProfile.as_view(), name = "edit_profile"),
    
    path('signup/', views.Signup.as_view(), name= "signup"),
	path('login/', auth.LoginView.as_view(template_name="accounts/registration/login.html"), name= "login"),
	path('logout/', auth.LogoutView.as_view(), name= "logout"),
    
    
    #section of reset password  
    
    path('password-reset/', auth.PasswordResetView.as_view(template_name="accounts/registration/password_reset.html", 
    email_template_name="accounts/registration/password_reset_email.html",success_url=reverse_lazy("accounts:password_reset_done")),name= "password_reset"),
    
    path('password-reset/done/', auth.PasswordResetDoneView.as_view(template_name="accounts/registration/password_reset_done.html"),
    name= "password_reset_done"),
    
    path('reset/<uidb64>/<token>/',auth.PasswordResetConfirmView.as_view(template_name="accounts/registration/password_reset_confirm.html",success_url=reverse_lazy("accounts:password_reset_complete")),
    name="password_reset_confirm"),
    
    path('reset/done/',auth.PasswordResetCompleteView.as_view(template_name="accounts/registration/password_reset_complete.html"),
    name="password_reset_complete")

    
    
    
]

chat_application/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [   
    path('', include('accounts.urls' , namespace= 'accounts')),
    path('', include('chats.urls' , namespace= 'chats')),
    path('', include('friends.urls' , namespace= 'friends')),
    path('admin/', admin.site.urls),   
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chats/urls.py
from django.urls import path
from . import views

app_name = "chats"

urlpatterns = [
    
    path('', views.chat, name = "chat"),
    path('chat/<str:username>/', views.chat_detail, name = "chat_detail"),
   
]

friends/urls.py
from django.urls import path
from . import views

app_name = "friends"

urlpatterns = [
    
    path('search/', views.search_friend, name = "search"),
    path('notification/', views.notification, name = "notification"),

    path('follow/<str:username>/', views.follow, name = "follow"),
    path('unfollow/<str:username>/', views.unfollow, name = "unfollow"),
    
    path('accept_follower/<str:username>/', views.accept_follower, name = "accept_follower"),
    path('remove_follower/<str:username>/', views.remove_follower, name = "remove_follower"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	{% block title %}
	{% endblock %}
    <link  href="{% static 'css/styles.css' %}" rel="stylesheet">
    <link  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
</head>
<body>
    <div class="frame">
        <!-- Contacts Sidebar -->
        <div class="contacts-area" class="content">     
                <div class="action-buttons">
                    
                   <a href="{% url 'friends:search' %}"><button class="settings"><i class="fa fa-search"></i></button></a>
                    <a href="{% url 'chats:chat' %}"><button class="add-contact"><i class="fa fa-message"></i><span class="badge ">{{messages_length}}</span></button></a>
                    <a href="{% url 'friends:notification' %}"><button class="notifications"><i class="fa fa-bell"></i><span class="badge ">{{ notifications_length }}</span></button></a>
                  <a href="{% url 'accounts:settings' %}"><button class="settings"><i class="fa fa-cog"></i></button></a>
                </div>
            

            
           {% block content %}
		   {% endblock %}
        </div>
    </div>
	{% block script %}
	{% endblock %}
    
</body>
</html>